### ISSUE TITLE
Decimal conversion

### ISSUE THREAD

**Issue by vri-sst** [mariokonrad/marnav#27]
Hi,

Thank you for this really good library. I am using it to cast NMEA frames in my developments.

But, I encountered some troubles when I used it with my locale french computer. During NMEA parsing (from string to numerical values), a call to the std::atod is made to convert string to double. But this function depends on current locale and causes troubles and throws exception :
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  invalid string to convert to double: [250.5]

I had to modify my current locale by "std::setlocale(LC_ALL, "C");" to avoid errors. Is it possible to integrate this modification in your code?

Thanks again for your work.
-- 
VRI

**Comment by mariokonrad** [comment]
Hi,

Thanks for the compliments.

Also, thank you for reporting the issue. Indeed, the functions to convert string/double all honor the locale. This is, as you point out, at least unfortunate. The handling of numbers for the communication protocol should not be dependent on the locale.

I think the library should not set the locale as you describe, because this setting is global. Another part of the software might be dependent on a specific locale.

Setting the locale seems to work for you now, but I agree, this is not handy nor should it be necessary. From my point of view, it's a bug. I'll make changes/enhancements to get independent from locales, but I can't promise a date ;-)

**Comment by vri-sst** [comment]
Thx a lot!
