### ISSUE TITLE
Any guesses how well this would work on a microcontroller?

### ISSUE THREAD

**Issue by bryceschober** [mariokonrad/marnav#5]

**Comment by mariokonrad** [comment]
Depends heavily on the microcontroller and its surrounding hardware. The library was written with focus on (at least) 32bit architectures, for ease of use (see README.md, chapter "Goals"). Minimal footprint in both size and CPU cycles was not a focus. For example, the library is IMHO quite usable on Raspberry2 (with Debian, GCC 4.9). It also uses dynamic memory and exceptions, which are often not available on small scale hardware.

Portability of the code should not be the big issue, but I doubt it is usable on a small hardware, for example with 256kB of RAM/ROM.

Besides the question: since you opened it, what's the issue?

**Comment by mariokonrad** [comment]
Due to lack of communication, this issue is closed.
